### scikit learn documentation
http://scikit-learn.org/stable/modules/feature_extraction.html#common-vectorizer-usage

In [29]:
from sklearn.feature_extraction.text import CountVectorizer
import copy
import numpy as np

In [30]:
vectorizer = CountVectorizer()
vectorizer

CountVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 1), preprocessor=None, stop_words=None,
        strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
        tokenizer=None, vocabulary=None)

In [31]:
corpus = [
       'This is the first document.',
        'This is the second second document.',
        'And the third one.',
       'Is this the first document?',]
X = vectorizer.fit_transform(corpus)
X = X.toarray()
X

array([[0, 1, 1, 1, 0, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 2, 1, 0, 1],
       [1, 0, 0, 0, 1, 0, 1, 1, 0],
       [0, 1, 1, 1, 0, 0, 1, 0, 1]], dtype=int64)

In [32]:
names = vectorizer.get_feature_names()
names

['and', 'document', 'first', 'is', 'one', 'second', 'the', 'third', 'this']

In [33]:
X_mask = copy.copy(X)
X_mask[X_mask>0]=1
X_mask

array([[0, 1, 1, 1, 0, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 1, 0, 1],
       [1, 0, 0, 0, 1, 0, 1, 1, 0],
       [0, 1, 1, 1, 0, 0, 1, 0, 1]], dtype=int64)

In [35]:
Y = np.dot(X.T, X_mask)
Y

array([[1, 0, 0, 0, 1, 0, 1, 1, 0],
       [0, 3, 2, 3, 0, 1, 3, 0, 3],
       [0, 2, 2, 2, 0, 0, 2, 0, 2],
       [0, 3, 2, 3, 0, 1, 3, 0, 3],
       [1, 0, 0, 0, 1, 0, 1, 1, 0],
       [0, 2, 0, 2, 0, 2, 2, 0, 2],
       [1, 3, 2, 3, 1, 1, 4, 1, 3],
       [1, 0, 0, 0, 1, 0, 1, 1, 0],
       [0, 3, 2, 3, 0, 1, 3, 0, 3]], dtype=int64)

In [36]:
def get_number(a,b,m,name):
    a_num = name.index(a)
    b_num = name.index(b)
    
    return m[a_num,b_num]

In [38]:
a = 'second'
b = 'this'
print(get_number(a,b,Y,names))
print(get_number(b,a,Y,names))

2
1


In [40]:
## you can convert it to symetric matrix if you want, by taking the max or min 
## i will do the min here, as it is closer to a rolling window calculation 
co_max = np.maximum(Y,Y.T)
np.fill_diagonal(co_max,0)
co_max

array([[0, 0, 0, 0, 1, 0, 1, 1, 0],
       [0, 0, 2, 3, 0, 2, 3, 0, 3],
       [0, 2, 0, 2, 0, 0, 2, 0, 2],
       [0, 3, 2, 0, 0, 2, 3, 0, 3],
       [1, 0, 0, 0, 0, 0, 1, 1, 0],
       [0, 2, 0, 2, 0, 0, 2, 0, 2],
       [1, 3, 2, 3, 1, 2, 0, 1, 3],
       [1, 0, 0, 0, 1, 0, 1, 0, 0],
       [0, 3, 2, 3, 0, 2, 3, 0, 0]], dtype=int64)

In [41]:
co_max - co_max.T ## to check if it is actually diagonal 

array([[0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=int64)